language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
# install from the zip file to see if files were forgotten
- python setup.py sdist --dist-dir=dist --formats=zip
- ( cd dist ; pip install hanging_threads-${PACKAGE_VERSION}.zip )
script:
# Test relative import
- python -m "hanging_threads"
# Test installed package import
- ( cd / && python -m "hanging_threads" )
